// <auto-generated />
using System;
using DetailViewer.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DetailViewer.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250711121112_AddInheritanceToESKDNumber")]
    partial class AddInheritanceToESKDNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("DetailViewer.Core.Models.Classifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Classifier");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.DocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssemblyNumberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ESKDNumberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManualDetailNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductNumberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YASTCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyNumberId");

                    b.HasIndex("ESKDNumberId");

                    b.HasIndex("ProductNumberId");

                    b.ToTable("DocumentRecords");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.ESKDNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("DetailNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassifierId");

                    b.ToTable("ESKDNumbers");

                    b.HasDiscriminator().HasValue("ESKDNumber");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DetailViewer.Core.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.AssemblyESKDNumber", b =>
                {
                    b.HasBaseType("DetailViewer.Core.Models.ESKDNumber");

                    b.HasDiscriminator().HasValue("AssemblyESKDNumber");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.ProductESKDNumber", b =>
                {
                    b.HasBaseType("DetailViewer.Core.Models.ESKDNumber");

                    b.HasDiscriminator().HasValue("ProductESKDNumber");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.DocumentRecord", b =>
                {
                    b.HasOne("DetailViewer.Core.Models.AssemblyESKDNumber", "AssemblyNumber")
                        .WithMany()
                        .HasForeignKey("AssemblyNumberId");

                    b.HasOne("DetailViewer.Core.Models.ESKDNumber", "ESKDNumber")
                        .WithMany()
                        .HasForeignKey("ESKDNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetailViewer.Core.Models.ProductESKDNumber", "ProductNumber")
                        .WithMany()
                        .HasForeignKey("ProductNumberId");

                    b.Navigation("AssemblyNumber");

                    b.Navigation("ESKDNumber");

                    b.Navigation("ProductNumber");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.ESKDNumber", b =>
                {
                    b.HasOne("DetailViewer.Core.Models.Classifier", "ClassNumber")
                        .WithMany("ESKDNumbers")
                        .HasForeignKey("ClassifierId");

                    b.Navigation("ClassNumber");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.Classifier", b =>
                {
                    b.Navigation("ESKDNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
