// <auto-generated />
using System;
using DetailViewer.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DetailViewer.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250710090415_UpdateProfileEntity")]
    partial class UpdateProfileEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("DetailViewer.Core.Models.DocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("YASTCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DocumentRecords");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.DocumentRecord", b =>
                {
                    b.OwnsOne("DetailViewer.Core.Models.ESKDNumber", "ESKDNumber", b1 =>
                        {
                            b1.Property<int>("DocumentRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CompanyCode")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DetailNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Version")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DocumentRecordId");

                            b1.ToTable("DocumentRecords");

                            b1.WithOwner()
                                .HasForeignKey("DocumentRecordId");

                            b1.OwnsOne("DetailViewer.Core.Models.Classifier", "ClassNumber", b2 =>
                                {
                                    b2.Property<int>("ESKDNumberDocumentRecordId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Name")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Number")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("ESKDNumberDocumentRecordId");

                                    b2.ToTable("DocumentRecords");

                                    b2.WithOwner()
                                        .HasForeignKey("ESKDNumberDocumentRecordId");
                                });

                            b1.Navigation("ClassNumber");
                        });

                    b.Navigation("ESKDNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
