// <auto-generated />
using System;
using DetailViewer.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DetailViewer.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250710114438_MakeClassifierAnEntity")]
    partial class MakeClassifierAnEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("DetailViewer.Core.Models.DocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ESKDNumberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("YASTCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ESKDNumberId");

                    b.ToTable("DocumentRecords");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.ESKDNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("DetailNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ESKDNumbers");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.DocumentRecord", b =>
                {
                    b.HasOne("DetailViewer.Core.Models.ESKDNumber", "ESKDNumber")
                        .WithMany()
                        .HasForeignKey("ESKDNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ESKDNumber");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.ESKDNumber", b =>
                {
                    b.OwnsOne("DetailViewer.Core.Models.Classifier", "ClassNumber", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Number")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.ToTable("Classifiers");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("ClassNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
