// <auto-generated />
using System;
using DetailViewer.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DetailViewer.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("DetailViewer.Core.Models.Classifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Classifiers");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.DocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ESKDNumberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("YASTCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ESKDNumberId");

                    b.ToTable("DocumentRecords");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.ESKDNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("DetailNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassifierId");

                    b.ToTable("ESKDNumbers");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.DocumentRecord", b =>
                {
                    b.HasOne("DetailViewer.Core.Models.ESKDNumber", "ESKDNumber")
                        .WithMany()
                        .HasForeignKey("ESKDNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ESKDNumber");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.ESKDNumber", b =>
                {
                    b.HasOne("DetailViewer.Core.Models.Classifier", "ClassNumber")
                        .WithMany("ESKDNumbers")
                        .HasForeignKey("ClassifierId");

                    b.Navigation("ClassNumber");
                });

            modelBuilder.Entity("DetailViewer.Core.Models.Classifier", b =>
                {
                    b.Navigation("ESKDNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
